 
(DRIVE TRUCK0 DEPOT0 MARKET1)
(BUY-ALL TRUCK0 GOODS6 MARKET1)
 
 
(DRIVE TRUCK0 MARKET1 MARKET9)
(BUY-ALL TRUCK0 GOODS1 MARKET9)
 
  
(DRIVE TRUCK0 MARKET9 MARKET1)
(BUY-ALL TRUCK0 GOODS5 MARKET1)
 
 
(DRIVE TRUCK0 MARKET1 MARKET7)
(BUY-ALL TRUCK0 GOODS4 MARKET7)
 
  
(DRIVE TRUCK0 MARKET7 MARKET8)
(BUY-ALL TRUCK0 GOODS0 MARKET8)
 
  
(DRIVE TRUCK0 MARKET8 MARKET3)
(BUY-ALL TRUCK0 GOODS5 MARKET3)
 
 
(DRIVE TRUCK0 MARKET3 MARKET10)
(BUY-ALL TRUCK0 GOODS5 MARKET10)
 
  
(DRIVE TRUCK0 MARKET10 MARKET7)
(BUY-ALLNEEDED TRUCK0 GOODS5 MARKET7)
 
  
(DRIVE TRUCK0 MARKET7 MARKET3)
(BUY-ALLNEEDED TRUCK0 GOODS0 MARKET3)
 
  
(DRIVE TRUCK0 MARKET3 MARKET7)
(BUY-ALL TRUCK0 GOODS3 MARKET7)
 
  
(DRIVE TRUCK0 MARKET7 MARKET1)
(BUY-ALL TRUCK0 GOODS3 MARKET1)
 
  
(DRIVE TRUCK0 MARKET1 MARKET6)
(BUY-ALL TRUCK0 GOODS3 MARKET6)
 
(DRIVE TRUCK0 MARKET6 MARKET3) 
 
(DRIVE TRUCK0 MARKET3 MARKET2)
(BUY-ALL TRUCK0 GOODS3 MARKET2)

  
(DRIVE TRUCK0 MARKET2 MARKET8)
(BUY-ALL TRUCK0 GOODS3 MARKET8)
 
 
(DRIVE TRUCK0 MARKET8 MARKET4)
(BUY-ALL TRUCK0 GOODS3 MARKET4)
 
 
(DRIVE TRUCK0 MARKET4 MARKET3)
(BUY-ALL TRUCK0 GOODS2 MARKET3)
 
  
(DRIVE TRUCK0 MARKET3 MARKET9)
(BUY-ALLNEEDED TRUCK0 GOODS3 MARKET9)
 
  
(DRIVE TRUCK0 MARKET9 MARKET6)
(BUY-ALLNEEDED TRUCK0 GOODS6 MARKET6)
 
 
(DRIVE TRUCK0 MARKET6 MARKET1)
(BUY-ALLNEEDED TRUCK0 GOODS1 MARKET1)
 
(DRIVE TRUCK0 MARKET1 MARKET9) 
(DRIVE TRUCK0 MARKET9 DEPOT0) 
  
(DRIVE TRUCK0 DEPOT0 MARKET2)
(BUY-ALLNEEDED TRUCK0 GOODS4 MARKET2)
 
(DRIVE TRUCK0 MARKET2 DEPOT0) 
  
(DRIVE TRUCK0 DEPOT0 MARKET4)
(BUY-ALL TRUCK0 GOODS2 MARKET4)
 
(DRIVE TRUCK0 MARKET4 DEPOT0) 
 
(DRIVE TRUCK0 DEPOT0 MARKET2)
(BUY-ALL TRUCK0 GOODS2 MARKET2)
  
(DRIVE TRUCK0 MARKET2 DEPOT0) 
  
(DRIVE TRUCK0 DEPOT0 MARKET7)
(BUY-ALL TRUCK0 GOODS2 MARKET7)
 
(DRIVE TRUCK0 MARKET7 DEPOT0) 
  
(DRIVE TRUCK0 DEPOT0 MARKET1)
(BUY-ALL TRUCK0 GOODS2 MARKET1)
 
(DRIVE TRUCK0 MARKET1 DEPOT0) 
  
(DRIVE TRUCK0 DEPOT0 MARKET9)
(BUY-ALLNEEDED TRUCK0 GOODS2 MARKET9)
 
(DRIVE TRUCK0 MARKET9 DEPOT0) 

