(drive-buy-all truck0 depot0 goods0 market3)
(drive-buy-all truck0 market3 goods0 market1)
(drive-buy-all truck0 market1 goods1 market3)
(drive truck0 market3 market4)
(buy-allneeded truck0 goods1 market4)
(drive-buy-all truck0 market4 goods4 market3)
(drive truck0 market3 market5)
(buy-allneeded truck0 goods2 market5)
(drive-buy-all truck0 market5 goods4 market2)
(drive truck0 market2 market1)
(buy-allneeded truck0 goods4 market1)
(buy-all truck0 goods3 market1)
(drive-buy-allneeded truck0 market1 goods3 market2)
(drive truck0 market2 depot0)
