(drive-buy-allneeded truck0 depot0 goods2 market5)
(drive-buy-allneeded truck0 market5 goods3 market1)
(drive-buy-all truck0 market1 goods0 market3)
(drive-buy-allneeded truck0 market3 goods0 market4)
(buy-all truck0 goods1 market4)
(drive-buy-all truck0 market4 goods1 market3)
(drive truck0 market3 depot0)
