(drive-buy-all truck0 depot0 goods0 market3)
(drive-buy-allneeded truck0 market3 goods0 market4)
(drive-buy-all truck0 market4 goods1 market3)
(drive-buy-allneeded truck0 market3 goods1 market4)
(drive truck0 market4 depot0)
