(drive-buy-allneeded truck0 depot0 goods2 market9)
(drive-buy-allneeded truck0 market9 goods6 market1)
(drive-buy-all truck0 market1 goods7 market9)
(drive-buy-allneeded truck0 market9 goods7 market7)
(drive-buy-all truck0 market7 goods1 market1)
(drive-buy-allneeded truck0 market1 goods1 market8)
(drive-buy-all truck0 market8 goods4 market7)
(drive-buy-all truck0 market7 goods5 market1)
(drive-buy-allneeded truck0 market1 goods5 market7)
(drive-buy-allneeded truck0 market7 goods4 market2)
(drive-buy-all truck0 market2 goods0 market6)
(drive-buy-allneeded truck0 market6 goods0 market8)
(drive-buy-all truck0 market8 goods3 market2)
(drive-buy-all truck0 market2 goods3 market6)
(drive truck0 market6 market1)
(buy-all truck0 goods3 market1)
(drive-buy-all truck0 market1 goods3 market4)
(drive-buy-all truck0 market4 goods3 market7)
(drive-buy-all truck0 market7 goods3 market9)
(drive-buy-allneeded truck0 market9 goods3 market8)
(drive truck0 market8 depot0)
