(drive-buy-allneeded truck0 depot0 goods2 market4)
(buy-all truck0 goods5 market4)
(drive truck0 market4 market10)
(buy-allneeded truck0 goods5 market10)
(drive-buy-all truck0 market10 goods3 market1)
(drive-buy-all truck0 market1 goods3 market9)
(drive-buy-all truck0 market9 goods3 market4)
(buy-all truck0 goods0 market4)
(drive-buy-allneeded truck0 market4 goods0 market6)
(drive-buy-all truck0 market6 goods4 market7)
(drive truck0 market7 market1)
(buy-all truck0 goods4 market1)
(drive-buy-all truck0 market1 goods4 market2)
(drive-buy-all truck0 market2 goods1 market1)
(drive-buy-allneeded truck0 market1 goods1 market8)
(drive truck0 market8 depot0)
