(drive-buy-allneeded truck0 depot0 goods1 market1)
(drive-buy-all truck0 market1 goods0 market4)
(drive-buy-all truck0 market4 goods6 market1)
(drive-buy-allneeded truck0 market1 goods6 market6)
(drive-buy-all truck0 market6 goods5 market4)
(drive-buy-all truck0 market4 goods5 market1)
(drive-buy-allneeded truck0 market1 goods5 market10)
(buy-all truck0 goods4 market10)
(drive-buy-all truck0 market10 goods2 market1)
(buy-all truck0 goods3 market1)
(drive-buy-allneeded truck0 market1 goods4 market2)
(drive-buy-all truck0 market2 goods2 market6)
(drive-buy-all truck0 market6 goods2 market9)
(drive-buy-all truck0 market9 goods2 market7)
(drive-buy-all truck0 market7 goods2 market4)
(buy-all truck0 goods3 market4)
(drive-buy-all truck0 market4 goods3 market6)
(drive-buy-all truck0 market6 goods3 market2)
(drive-buy-all truck0 market2 goods3 market9)
(drive-buy-all truck0 market9 goods3 market7)
(drive truck0 market7 depot0)
